# Generated by Django 5.0.1 on 2024-02-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_name', models.CharField(max_length=25)),
                ('Contact', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=25)),
                ('Data_Employee', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Courses_name', models.CharField(max_length=10)),
                ('Courses_code', models.CharField(max_length=10)),
                ('Dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.staff'),
        ),
        migrations.CreateModel(
            name='Course_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_name', models.CharField(max_length=25)),
                ('Unit_code', models.CharField(max_length=20)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.courses')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Student_RegNo', models.CharField(max_length=25, unique=True)),
                ('Student_Email', models.EmailField(max_length=25)),
                ('Studen_Phone', models.CharField(max_length=25)),
                ('Reg_Date', models.DateField()),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.courses')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
        ),
    ]
